GoodDollar/GoodWeb3-Mono

- packages/sdk/src/core/staking.ts
- for loop parameter should not be in brackets
> fix: claim rewards loop

- .prettierrc
- .yarn/patches/web3-core-method-npm-1.7.5-919ae06220.patch
- package.json
- packages/sdk-v2/.prettierrc
- packages/sdk/package.json
- packages/sdk/src/contracts/FuseUniswapContract.ts
- packages/sdk/src/core/buy.ts
- packages/sdk/src/core/sell.ts
- packages/sdk/src/core/staking.ts
- packages/sdk/src/core/ubi.ts
- packages/sdk/src/functions/approve.ts
- yarn.lock
rely on defaults for gas price for both etherem + fuse
#9
> add: use network default gasprice for fuseswap

- packages/good-design/.ctirc
- packages/good-design/.gitignore
- packages/good-design/.prettierrc
- packages/good-design/.storybook/main.js
- packages/good-design/.storybook/preview.js
- packages/good-design/README.md
- packages/good-design/babel.config.js
- packages/good-design/metro.config.js
- packages/good-design/package.json
- packages/good-design/src/core/buttons/BaseButton.tsx
- packages/good-design/src/core/buttons/index.ts
- packages/good-design/src/core/provider/ThemeProvider.tsx
- packages/good-design/src/core/provider/index.ts
- packages/good-design/src/stories/Page.stories.tsx
- packages/good-design/src/stories/index.ts
- packages/good-design/tsconfig.json
Instead of bitdev, we will start with a storybook component library 
About # (original issue for bitdev, might be looked into at a later date)
#7
> add: basic storybook config with nativebase

- packages/good-design/src/core/modals/FVModal.tsx
- packages/sdk-v2/src/sdk/claim/react.ts
fix some issues regarding redirecting to FV flow and back
About #230
> (Bug) redirects fix

- packages/good-design/src/core/buttons/ActionButton.tsx
- packages/good-design/src/core/buttons/BaseButton.tsx
- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/core/layout/Layout.tsx
- packages/good-design/src/core/layout/Title.tsx
- packages/good-design/src/core/modals/cross.native.tsx
- packages/good-design/src/core/modals/cross.tsx
- packages/sdk-v2/src/hooks/useAppRestart.tsx
- packages/sdk-v2/src/hooks/useAppState.tsx
- packages/sdk-v2/src/hooks/useRefreshOrNever.tsx
- packages/sdk-v2/src/sdk/analytics/google/api.native.ts
- packages/sdk-v2/src/sdk/analytics/google/api.ts
- unnamed default exports been removed
> (Chore) Remove unnamed default exports

- packages/sdk-v2/src/sdk/analytics/amplitude/Amplitude.ts
- packages/sdk-v2/src/sdk/analytics/indicative/api.ts
Minor fix for analytics
Locally with dev dashboard
> Bug: Amplitude/Indicative fix

- packages/good-design/src/core/layout/Title.tsx
- packages/good-design/src/core/modals/BasicModal.tsx
Overlay for action modal on claim screen did not show properly, this fixes it
> Hotfix for overlay action modal

- packages/sdk-v2/src/sdk/openlogin/i18n.ts
- packages/sdk-v2/src/sdk/openlogin/react.tsx
- packages/sdk-v2/src/sdk/openlogin/sdk.ts
- packages/sdk-v2/src/sdk/openlogin/types.ts
[About #275](https://github.com/GoodDollar/GoodProtocolUI/issues/274)
> (Chore) Login SDK should update customization (whitelabel) settings

- package.json
- packages/good-design/package.json
- packages/good-design/src/apps/bridge/MicroBridge.tsx
- packages/good-design/src/apps/bridge/MicroBridgeController.tsx
- packages/good-design/src/core/inputs/TokenInput.tsx
- packages/good-design/src/core/inputs/TokenOutput.tsx
- packages/good-design/src/core/layout/BalanceGD.tsx
- packages/good-design/src/custom.d.ts
- packages/sdk-v2/package.json
- packages/sdk-v2/src/contexts/Web3Context.tsx
- packages/sdk-v2/src/sdk/base/react.ts
- packages/sdk-v2/src/sdk/constants.ts
- packages/sdk-v2/src/sdk/savings/react.ts
- yarn.lock
About [#284](https://github.com/GoodDollar/GoodProtocolUI/issues/284)
> (Feature) G$ Decimals should be dynamic based on token 

- packages/good-design/src/apps/bridge/MicroBridge.tsx
- packages/good-design/src/apps/bridge/MicroBridgeController.tsx
- added microbridge callbacks
- TODO: swap & wc callbacks
About [#268](https://github.com/GoodDollar/GoodProtocolUI/issues/268)
> (Feature) Add events & callbacks needed for new features

- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/analytics/mixpanel/api.native.ts
- packages/sdk-v2/src/sdk/analytics/mixpanel/api.ts
- packages/sdk-v2/src/sdk/analytics/mixpanel/index.ts
- packages/sdk-v2/src/sdk/analytics/mixpanel/mixpanel.ts
- packages/sdk-v2/src/sdk/analytics/posthog/index.ts
- packages/sdk-v2/src/sdk/analytics/posthog/posthog.ts
- packages/sdk-v2/src/sdk/analytics/sdk.ts
- packages/sdk-v2/src/sdk/analytics/types.ts
- packages/sdk-v2/src/stories/analytics/Mixpanel.stories.tsx
- packages/sdk-v2/src/stories/analytics/PostHog.stories.tsx
- yarn.lock
- added support for mixpanel and posthog
- tested basic integration for web via stories (native not tested)
> add: mixpanel and posthog

- packages/good-design/package.json
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/claim/react.ts
- yarn.lock
Add hook to check if connected account has any claimable UBI on a supported chain
**About**
https://github.com/GoodDollar/GoodProtocolUI/pull/336
> add hasclaimed hook

- packages/good-design/package.json
- packages/good-design/src/advanced/web3action/Web3Action.tsx
- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/custom.d.ts
- packages/good-design/src/theme/hoc/withTheme.tsx
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/claim/react.ts
- yarn.lock
Claim button flow described here: https://github.com/GoodDollar/GoodProtocolUI/issues/315#issuecomment-1436836152
> (Draft) Bug: fix claim button flow

- packages/good-design/package.json
- packages/good-design/src/core/layout/ClaimCarousel.tsx
- packages/good-design/src/custom.d.ts
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- yarn.lock
minor fix for viewport cutting off the cards.
retested pagination, seems to be shown as intended
https://github.com/GoodDollar/GoodProtocolUI/issues/319
> 319 fix claim cards

- packages/sdk/src/constants/graphql.ts
- packages/sdk/src/hooks/useEnvWeb3.ts
https://thegraph.com/hosted-service/subgraph/aave/protocol-v2 (fails to load)
https://github.com/aave/protocol-subgraphs/issues/99 (issue is raised)
https://github.com/GoodDollar/GoodProtocolUI/issues/367
> Bug: Staking/Portfolio not loading #367 

- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/core/layout/ClaimCarousel.tsx
- packages/good-design/src/custom.d.ts
- yarn.lock
Fixing pagination and viewport
https://github.com/GoodDollar/GoodProtocolUI/issues/319
> fix: pagination and viewport width

- packages/good-design/package.json
- packages/good-design/src/core/layout/ClaimCarousel.tsx
- packages/good-design/src/custom.d.ts
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- yarn.lock
Desktop users could not slide through the cards caroussel.
Added a click to slide on the pagination
https://github.com/GoodDollar/GoodProtocolUI/issues/371
> Fix: add click to slide to caroussel

- packages/good-design/package.json
- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/custom.d.ts
- yarn.lock
Fix for trigger to open modal when whitelist status is delayed to fetch was not working properly
#71 
> Fix: 71 delayed whitelist fetching

- packages/good-design/package.json
- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/core/buttons/LearnButton.tsx
- packages/good-design/src/core/buttons/index.ts
- packages/good-design/src/core/web3/KimaModal.tsx
- packages/good-design/src/core/web3/SwitchChainModal.tsx
- packages/good-design/src/core/web3/index.ts
- packages/good-design/src/stories/core/web3/KimaModal.stories.tsx
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- yarn.lock
Adding a modal to be shown based on bridge-status.
https://github.com/GoodDollar/GoodProtocolUI/issues/389
> 389: add kima modal

- packages/good-design/package.json
- packages/good-design/src/stories/apps/magik/Magik.stories.tsx
- yarn.lock
Added Magik Widget component story for G$ offramp integration.
**Dependencies Required:**
- @magiklabs/react-sdk
We have tested this code in production, and been able to successfully offramp G$ to bank accounts in India and Philippines.
> Feature: Added Magik Widget story to good-design

- packages/good-design/package.json
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/contexts/Web3Context.tsx
- packages/sdk-v2/src/sdk/base/sdk.ts
- yarn.lock
Adding hook for sdk-v2 web3context
https://github.com/GoodDollar/GoodProtocolUI/pull/433
> add: hook for use web3context

- packages/sdk-v2/src/sdk/claim/sdk.ts
- packages/sdk-v2/src/stories/claim/ClaimFlowSimple.stories.tsx
Add an sdk to delete user FV record
> add: deletefvrecord

- .eslintrc.cjs
- dev-release
- packages/good-design/package.json
- packages/good-design/src/advanced/customswitch/CustomSwitch.tsx
- packages/good-design/src/advanced/customswitch/SelectBox.theme.ts
- packages/good-design/src/core/modals/BasicModal.tsx
- packages/good-design/src/core/web3/GoodIdModal.tsx
- packages/good-design/src/core/web3/index.ts
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/claim/sdk.ts
- yarn.lock
Modal + component for showing face-id sig
https://github.com/GoodDollar/GoodProtocolUI/issues/456
As per requested UI
(desktop)
(mobile)
> 456 goodid modal

- packages/good-design/package.json
- packages/good-design/src/apps/onramp/GdOnramperWidget.tsx
- packages/good-design/src/core/buttons/ClaimButton.tsx
- packages/good-design/src/core/modals/BasicModal.tsx
- packages/good-design/src/core/web3/WalletAndChainGuard.tsx
- packages/good-design/src/core/web3/index.ts
- packages/good-design/src/core/web3/modals/GoodIdModal.tsx
- packages/good-design/src/core/web3/modals/KimaModal.tsx
- packages/good-design/src/core/web3/modals/RedirectModal.tsx
- packages/good-design/src/core/web3/modals/SwitchChainModal.tsx
- packages/good-design/src/core/web3/modals/index.ts
- packages/good-design/src/hooks/index.ts
- packages/good-design/src/hooks/useRedirectNoticeModal.tsx
- packages/good-design/src/stories/apps/bridge/MicroBridgeController.stories.tsx
- packages/sdk-v2/package.json
- yarn.lock
Adding modal for external redirect notice
https://github.com/GoodDollar/GoodProtocolUI/issues/520
(Mobile)
(Desktop)
> Add: 520-redirect notice

- packages/good-design/package.json
- packages/good-design/src/apps/newsfeed/NewsFeed.tsx
- packages/good-design/src/core/layout/ClaimCard.tsx
- packages/good-design/src/core/layout/ClaimCarousel.tsx
- packages/good-design/src/core/layout/SlideDownTab.tsx
- packages/good-design/src/hooks/useScreenSize.ts
- packages/good-design/src/theme/theme.ts
- packages/sdk-v2/package.json
- yarn.lock
Align the theme and several components with the updated page layout for gooddapp
https://github.com/GoodDollar/GoodProtocolUI/issues/519
> 519 theme update

- packages/good-design/package.json
- packages/good-design/src/apps/redtent/RedtentController.tsx
- packages/good-design/src/apps/redtent/RedtentWizard.tsx
- packages/good-design/src/core/animated/SpinnerCheckMark.tsx
- packages/good-design/src/core/buttons/BaseButton.tsx
- packages/good-design/src/core/buttons/GoodButton.tsx
- packages/good-design/src/core/buttons/index.ts
- packages/good-design/src/core/buttons/theme.ts
- packages/good-design/src/core/inputs/WebVideoUploader.native.tsx
- packages/good-design/src/core/inputs/WebVideoUploader.web.tsx
- packages/good-design/src/hooks/useWindowFocus.native.ts
- packages/good-design/src/stories/apps/redtent/Redtent.stories.tsx
- packages/good-design/src/stories/apps/redtent/RedtentS3.stories.tsx
- packages/good-design/src/utils/WizardContext.tsx
- packages/good-design/tsconfig.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/index.ts
- packages/sdk-v2/src/sdk/redtent/index.ts
- packages/sdk-v2/src/sdk/redtent/react.ts
- packages/sdk-v2/src/sdk/redtent/sdk.ts
- packages/sdk-v2/src/stories/redtent/Redtent.stories.tsx
- yarn.lock
Added basic wizard + sdks for uploading video and registering to redtent
> [GoodID] 122 Redtent Offer

- packages/good-design/package.json
- packages/good-design/src/apps/goodid/components/GoodIdCard.tsx
- packages/good-design/src/apps/goodid/components/SegmentationRow.tsx
- packages/good-design/src/apps/goodid/components/theme.ts
- packages/good-design/src/apps/goodid/screens/DisputeThanks.tsx
- packages/good-design/src/apps/goodid/screens/OffersAgreement.tsx
- packages/good-design/src/apps/goodid/screens/OnboardScreen.tsx
- packages/good-design/src/apps/goodid/screens/SegmentationDispute.tsx
- packages/good-design/src/apps/goodid/screens/SegmentationScreen.tsx
- packages/good-design/src/apps/goodid/screens/theme.ts
- packages/good-design/src/apps/goodid/wizards/RedtentWizard.tsx
- packages/good-design/src/apps/goodid/wizards/WizardHeader.tsx
- packages/good-design/src/stories/apps/goodid/GoodId.stories.tsx
- packages/good-design/src/stories/apps/redtent/Redtent.stories.tsx
- packages/good-design/src/theme/theme.ts
- packages/sdk-v2/package.json
- yarn.lock
Applied changes to handle responsiveness correctly based on current designs.
This solely applies to our current designs fitting the screens of gooddapp/wallet.
If alternative dimensions are needed for 3rd parties they can do so by overriding the baseStyles through extending native-base theme.
> Goodid responsiveness fixes

- .yarnrc.yml
- packages/good-design/package.json
- packages/good-design/src/apps/bridge/MicroBridge.tsx
- packages/good-design/src/apps/bridge/MicroBridgeController.tsx
- packages/good-design/src/apps/bridge/MicroBridgeStatus.tsx
- packages/good-design/src/apps/bridge/types.ts
- packages/good-design/src/apps/bridge/useBalanceHook.ts
- packages/good-design/src/apps/bridge/wizard/BridgeWizard.tsx
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/base/react.ts
- packages/sdk-v2/src/sdk/constants.ts
- packages/sdk-v2/src/sdk/microbridge/react.ts
- packages/sdk-v2/src/stories/microbridge/MicrobridgeHooks.stories.tsx
- yarn.lock
> add: misc fixes

- packages/good-design/src/core/buttons/LearnButton.tsx
Updated the link from https://gooddollar.notion.site/How-do-transactions-work-in-web3-ccf11b4e16874a1682722a20c4e24742 to https://docs.gooddollar.org/frequently-asked-questions/using-gooddollar#how-do-transactions-work-in-web3
About #211
> Fix | Update link in Waiting for Confirmation modal |

- .github/workflows/preview-storybook.yml
- packages/good-design/package.json
- packages/good-design/src/apps/goodid/controllers/OnboardController.tsx
- packages/good-design/src/apps/goodid/controllers/SegmentationController.tsx
- packages/good-design/src/apps/goodid/wizards/RedtentWizard.tsx
- packages/good-design/src/apps/goodid/wizards/SegmentationWizard.tsx
- packages/good-design/src/apps/ubi/context/ClaimContext.tsx
- packages/good-design/src/apps/ubi/wizard/ClaimWizard.tsx
- packages/good-design/src/core/web3/modals/YouSureModal.tsx
- packages/sdk-v2/package.json
- packages/sdk-v2/src/sdk/analytics/react.tsx
- packages/sdk-v2/src/sdk/analytics/types.ts
- storybook-release
- yarn.lock
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> 168 goodid events

- packages/good-design/src/apps/goodid/controllers/OnboardController.tsx
- packages/good-design/src/apps/goodid/controllers/SegmentationController.tsx
- packages/good-design/src/apps/goodid/wizards/SegmentationWizard.tsx
- packages/good-design/src/apps/ubi/wizard/ClaimWizard.tsx
- packages/sdk-v2/src/sdk/goodid/react.ts
Adds the following events to goodid grouped under `goodid_error`:
-- when checking expiry or goto face-verification failed
-- when dapp fails to handle onDone
-- when requesting/issueing certificates failed
-- when verifying eligibility for offers fails for an unknown reason
-- when one or more claims fail
> Goodid error tracking

- packages/good-design/.storybook/preview.js
- packages/good-design/package.json
- packages/good-design/src/core/layout/BalanceGD.tsx
- packages/good-design/src/core/web3/modals/ErrorModal.tsx
- packages/good-design/src/stories/W3Wrapper.tsx
- packages/good-design/src/stories/core/modals/BasicModal.stories.tsx
- packages/login-sdk/package.json
- packages/sdk-v2/package.json
- packages/sdk-v2/src/contexts/Web3Context.tsx
- packages/sdk-v2/src/sdk/base/hooks/useGasFees.ts
- packages/sdk-v2/src/sdk/base/react.ts
- packages/sdk-v2/src/sdk/claim/react.ts
- packages/sdk-v2/src/sdk/constants.ts
- packages/sdk-v2/src/sdk/faucet/react.ts
- packages/sdk-v2/src/sdk/index.ts
- packages/sdk-v2/src/sdk/reserve/index.ts
- packages/sdk-v2/src/sdk/reserve/react.tsx
- packages/sdk-v2/src/stories/reserve/ReserveHooks.stories.tsx
- packages/sdk-v2/tsconfig.json
- packages/sdk/package.json
- packages/sdk/src/constants/addresses.ts
- packages/sdk/src/constants/tokens.ts
- packages/sdk/src/core/buy.ts
- packages/sdk/src/core/sell.ts
- packages/sdk/src/core/swap.ts
- packages/sdk/src/core/tokens.ts
- packages/sdk/src/methods/calculateExitContribution.ts
- packages/sdk/src/methods/tokenLists.ts
- yarn.lock
Add sdk support for mento reserve
Other changes
- improved token list
- fixed paperprovider missing in storybook
- added reason line for errormodal
- removed GDX support
TODO:
Integrate a new feature for handling Celo reserve functionalities, remove deprecated GDX token support, and enhance the reserve SDK by adding hooks and related stories in the GoodDollar project.
These changes introduce a new module for managing Celo reserves, reflecting a strategic direction to support Celo in the platform. The deprecated GDX support has been removed to clean up and modernize the codebase as the token is no longer in use. These enhancements ensure that the platform remains optimized and aligned with the current token strategy, while also extending the SDK's capabilities to facilitate seamless …
> Celo reserve
